# Generated by Django 2.2.13 on 2020-06-06 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='payloads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('heatindex_in_celsious', models.FloatField()),
                ('heatindex_in_farenheit', models.FloatField()),
                ('humidity', models.FloatField()),
                ('temperature_celsius', models.FloatField()),
                ('temperature_farenheit', models.FloatField()),
                ('Ammonia', models.FloatField()),
                ('carbon_dioxide', models.FloatField()),
                ('carbon_monoxide', models.FloatField()),
                ('sound_level', models.FloatField()),
            ],
        ),
    ]
