# Generated by Django 2.2.13 on 2020-06-06 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_hub', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='payloads',
            new_name='payload',
        ),
    ]
