# Generated by Django 2.2.13 on 2020-06-06 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_info', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='devices',
            new_name='device',
        ),
    ]
